### ISSUE TITLE
Remove the horrible 3 letter word 

### ISSUE THREAD

**Issue by ghost** [thebracket/noxfutura#6]
You have a file which starts with "NFRender", and ends with a horrible 3 letter word. That 3 letter word must not be used at all. And that stupidly named renderer debugger software (which starts with "Render" and ends with disgusting 3 letters word after) must be banned. 
I'm talking about that disgusting 3 letter word, which if I'm not mistaken, refers to a disgusting mainstream propaganda word used to promote arrogant idiots. If it's not referring to that filth, then apologizes for misunderstanding.

**Comment by thebracket** [comment]
This is a bit of a head-scratcher. ["Doc" is a standard English short-hand for "document" and "doctor"](https://www.yourdictionary.com/doc), I'm not aware of any slurs that use it? "RenderDoc" is a very descriptive name: it both *documents* your GPU workload and acts like a *doctor* gathering diagnostic information so you can fix your issues. I'm pretty sure Microsoft don't mean any ill-intent with `.doc` files (Word files), and sick people still make an appointment with their doctor?

Closing this issue, because I *really* can't figure out what you're asking about. You're welcome to reply with some documentation (heh) as to why it became a problem?
